
import type { Metadata } from 'next'
import { Montserrat } from 'next/font/google'
import TanstackProvider from './components/App/App'
import { StoreProvider } from './components/StoreProvider/StoreProvider'
import { GlobalStyle } from './global'

const font = Montserrat({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={font.className}>
        <StoreProvider>
          <TanstackProvider>
              <GlobalStyle/>
              {children}
    
          </TanstackProvider>
        </StoreProvider>
        </body>
    </html>
  )
}
